version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - .:/home/app
    environment:
      - SPRING_DEVTOOLS_REMOTE_SECRET=mysecret
      - SPRING_BOOT_DEVTOOLS_RESTART_ENABLED=true
